name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  release:
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
      fail-fast: false
    runs-on: ${{ matrix.image }}
    steps:
      - id: init
        name: Initialize
        uses: spotdemo4/nix-init@f88963412ff6a2e9c4dc40233e10729444aa7b05 # v1.31.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0
          shell: release

      - name: Publish to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ steps.init.outputs.token }}
          REGISTRY: ghcr.io
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub (script)
        if: matrix.image == 'ubuntu-24.04'
        env:
          GH_TOKEN: ${{ steps.init.outputs.token }}
        run: |
          # Publishing bash script

          echo "Inlining sources"
          ./.github/inline.sh ./src/flake-release.sh > flake-release.sh

          echo "Uploading to GitHub"
          gh release upload "$(git describe --tags --abbrev=0)" flake-release.sh

      - name: Publish to FlakeHub
        if: matrix.image == 'ubuntu-24.04'
        uses: DeterminateSystems/flakehub-push@71f57208810a5d299fc6545350981de98fdbc860 # v6
        with:
          visibility: public
